### ISSUE TITLE
New fatal error with xsl: PKIX path building failed ... unable to find valid certification path to requested target

### ISSUE THREAD

**Issue by emiliom** [NOAA-PMEL/uafnciso#16]
We have an nciso job that used to work just fine (ran daily) and now fails. It's using the latest release, 2.3.6, on an older Ubuntu server. I don't know how long it's been failing, but I suspect it's no more than 6 months. The error involves a failure to find a valid certificate for an external XSLT stylesheet. Here are the run-time messages for one of the end points, https://wilson.coas.oregonstate.edu/thredds/catalog.xml?dataset=OCOS

```
 INFO [main] (ServiceController.java:29) - Running createWaf in service controller...
 INFO [main] (CatalogCrawlerImpl.java:78) - maxDepth: 20 depth: 0 dataset.getFullName():OSU ROMS; dataset.hasAccess(): true maxLeaves: 1 leafcnt: 0
 INFO [main] (CatalogCrawlerImpl.java:82) - allowable service
 INFO [main] (CatalogCrawlerImpl.java:99) - adding mdc
 INFO [main] (WafService.java:45) - ncmlFilePath=/var/www/metadata/ioos/testncISO/ncml/wilson.xml
ERROR:  'Could not compile stylesheet'
FATAL ERROR:  'sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target'
           :sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
ERROR [main] (WafService.java:85) - thredds.server.metadata.exception.ThreddsUtilitiesException: Configuration problem: https://cdn.rawgit.com/NOAA-PMEL/uafnciso/fdb7f86515c21a8b5c087978975addf9ad5d0027/transforms/UnidataDDCount-HTML.xsl TransformerConfigurationException. sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
ERROR:  'Could not compile stylesheet'
FATAL ERROR:  'sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target'
           :sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
ERROR [main] (WafService.java:99) - thredds.server.metadata.exception.ThreddsUtilitiesException: Configuration problem: https://cdn.rawgit.com/noaaroland/uafnciso/e84d6e26b87a799eb996173358c72ec7a4ed4912/transforms/UnidataDD2MI.xsl TransformerConfigurationException. sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
```

It seems odd that the two urls on this error message are ones that in this [uafnciso commit](https://github.com/NOAA-PMEL/uafnciso/commit/9ef49eebfe979e5a6d21cabdd248657492d67a89) leading up to the latest release (2.3.6, the one I'm using), those two url's were replaced with different ones:

- https://cdn.jsdelivr.net/gh/NOAA-PMEL/uafnciso@fdb7f86515c21a8b5c087978975addf9ad5d0027/transforms/UnidataDDCount-HTML.xsl replaced https://cdn.rawgit.com/NOAA-PMEL/uafnciso/fdb7f86515c21a8b5c087978975addf9ad5d0027/transforms/UnidataDDCount-HTML.xsl
- https://cdn.jsdelivr.net/gh/NOAA-PMEL/uafnciso@a9f3dceb0dbc092f8d7f5153ceeb58af2d30edc4/transforms/UnidataDD2MI.xsl replaced https://cdn.rawgit.com/noaaroland/uafnciso/e84d6e26b87a799eb996173358c72ec7a4ed4912/transforms/UnidataDD2MI.xsl

But I've confirmed that the code file modified in that commit is in fact updated in the 2.3.6 source code zip file available for download.

cc @mwengren, @crisien 
ref https://github.com/nanoos-pnw/ioos-ws/issues/2

**Comment by noaaroland** [comment]
Can you please give me the command line you attempted when you got the error and information the JDK you're using (like maybe the output from java -version)?

This issue of getting a valid certificate is a problem doing some HTTP(S) tasks from some hosts using some Java environments.

Another thing you can do is download the XLST from your host with wget and specify it on the command line with the -xsl option. E.g.

```
wget https://cdn.jsdelivr.net/gh/NOAA-PMEL/uafnciso@fdb7f86515c21a8b5c087978975addf9ad5d0027/transforms/UnidataDDCount-HTML.xsl
java -Xms1024m -Xmx1024m -jar ncISO-2.3.6.jar -ts http://amb6400b.stccmop.org:8080/thredds/forecast_model_data.xml -num 125 -depth 100 -iso true -xsl UnidataDDCount-HTML.xsl
```

or whatever XSL is good for the task you are trying to accomplish with ncISO.

**Comment by emiliom** [comment]
Thanks @noaaroland . The command statement is below, followed by the response from `java -version`:

```bash
java -Xms1024m -Xmx1024m -jar ncISO-2.3.6.jar -ts https://wilson.coas.oregonstate.edu/thredds/catalog.xml?dataset=OCOS -num 1 -depth 20 -iso true -waf /var/www/metadata/ioos/testncISO

$ java -version
java version "1.7.0_45"
Java(TM) SE Runtime Environment (build 1.7.0_45-b18)
Java HotSpot(TM) 64-Bit Server VM (build 24.45-b08, mixed mode)
```

This server is getting long in the tooth, for sure.

I tried your suggestion with a local xsl downloaded from https://cdn.jsdelivr.net, and got the same error that reports failures with the two xsl files at https://cdn.rawgit.com. FYI, since the error reports two different xsl files, I tried the statement twice, once with `-xsl UnidataDDCount-HTML.xsl` and once with `-xsl UnidataDD2MI.xsl`, both unsuccessfully.

**Comment by noaaroland** [comment]
The short answer here is to upgrade to Java 8. I recommend OpenJDK. For what it's worth, the current version of Java is 15.

The long answer is that -xsl argument refers to a directory, not a file , but the software still tries to compile the default XSLT from the CDN even if that argument is included.
