### ISSUE TITLE
ISO metadata from ncml and/or netcdf file without THREDDs

### ISSUE THREAD

**Issue by theobarnhart-USGS** [NOAA-PMEL/uafnciso#20]
Is there a way to generate an ISO metadata xml file from a ncml and/or a netCDF file without access to a THREDDs server? For example, I have several hundred CF-compliant netCDF files on a HPC that I would like to publish, but the repository requires an ISO metadata file for each file.

Thank you!

**Comment by noaaroland** [comment]
ncISO uses services provided by the THREDDS Data Server to decompose the netCDF file and extract it to build its response, so it cannot read a file directly.
